python sov_entropy.py --language hu --filename ../data/wiki40b-txt-parsed/hu.test.conllu --outfile wiki40b-entropy/hu_lemma.csv --lemmatize
python sov_entropy.py --language hi --filename ../data/wiki40b-txt-parsed/hi.test.conllu --outfile wiki40b-entropy/hi_lemma.csv --lemmatize
python sov_entropy.py --language fa --filename ../data/wiki40b-txt-parsed/fa.test.conllu --outfile wiki40b-entropy/fa_lemma.csv --lemmatize
python sov_entropy.py --language tr --filename ../data/wiki40b-txt-parsed/tr.test.conllu --outfile wiki40b-entropy/tr_lemma.csv --lemmatize
python sov_entropy.py --language id --filename ../data/wiki40b-txt-parsed/id.test.conllu --outfile wiki40b-entropy/id_lemma.csv --lemmatize
python sov_entropy.py --language vi --filename ../data/wiki40b-txt-parsed/vi.test.conllu --outfile wiki40b-entropy/vi_lemma.csv --lemmatize
python sov_entropy.py --language fr --filename ../data/wiki40b-txt-parsed/fr.test.conllu --outfile wiki40b-entropy/fr_lemma.csv --lemmatize
python sov_entropy.py --language ru --filename ../data/wiki40b-txt-parsed/ru.test.conllu --outfile wiki40b-entropy/ru_lemma.csv --lemmatize
python sov_entropy.py --language de --filename ../data/wiki40b-txt-parsed/de.test.conllu --outfile wiki40b-entropy/de_lemma.csv --lemmatize
python sov_entropy.py --language en --filename ../data/wiki40b-txt-parsed/en.test.conllu --outfile wiki40b-entropy/en_lemma.csv --lemmatize